### ISSUE TITLE
could you help me about the issue?

### ISSUE THREAD

**Issue by newCoderForJS** [cropandweed/cropandweed-dataset#2]
I saw that you used Yolo to test your dataset. when I downloaded your dataset, I found its label format is CSV, I thought it was not supported by yolov5. I tried to calculate these numbers in the label file to convert them to ". txt", but I failed.  could you give me some advice about it? 

thank you so much.

**Comment by steiningerd** [comment]
For Yolov5 you need to convert the first four coordinates of our bounding box format (Left, Top, Right, Bottom) to a center point and dimensions (Center X, Center Y, Width, Height) normalized by image width or height, accordingly. The Label ID has to be moved to the beginning of the line. If you need more specific information, please tell me exactly where your conversion fails.

**Comment by newCoderForJS** [comment]
Thank you for your reply. 

I have coded for converting,  I think it worked.

If you are interested in it, I have added it to the attachment.

Thank you for your job.

[main_code.txt](https://github.com/cropandweed/cropandweed-dataset/files/12256136/main_code.txt)
