### ISSUE TITLE
while running setup.py, the downloading of dataset is always stuck to the 20%

### ISSUE THREAD

**Issue by skyhoudou** [cropandweed/cropandweed-dataset#3]
Hi, i am interested in the area of weed and crop detection. And i found your work very practical and interesting. I want to get access to the CropandWeed dataset. Following the specification, i run the setup.py. But everytime the downloading is stuck to the 20%. The message shown on the console is described as below:

downloading and extracting files:  20%|██        | 1/5 [00:26<01:44, 26.12s/it]

Is that caused by the pool HTTP connection?

**Comment by Daraan** [comment]
Hello, this is not an official answer,

the first part of the download (1/5) are just the annotations and much smaller. Part 2...5 are the images and will take a much longer to download.
Just stay patient.

Here the code reference:
https://github.com/cropandweed/cropandweed-dataset/blob/e471c47971af431f4fb8d7463f6b4c9e2b3b35fa/cnw/setup.py#L27C5-L32C38

**Comment by skyhoudou** [comment]
Thank you. I have already download all of them.

**Comment by thisisqiaoqiao** [comment]
您好，可以分享一下数据集嘛。目前网站下载不上。

**Comment by thisisqiaoqiao** [comment]
Can you share the dataset resources, I can't download it from my own network, thank you very much.
