### ISSUE TITLE
网站显示无权访问

### ISSUE THREAD

**Issue by thisisqiaoqiao** [cropandweed/cropandweed-dataset#4]
您好，下载的时候下载不动。打开网站显示无权访问，该怎样解决呢

**Comment by steiningerd** [comment]
I verified that the files can be downloaded. Are you sure you have writing permissions for your local directory?

**Comment by thisisqiaoqiao** [comment]
有权限写入，进度一直停留在0。
![image](https://github.com/cropandweed/cropandweed-dataset/assets/127526922/a7925fc4-a1f6-4b0f-b40b-3a99cb32858b)

**Comment by steiningerd** [comment]
How long does it stay at 0%? The download can take some time.

**Comment by thisisqiaoqiao** [comment]
问题解决了，我换了一台电脑能够正常下载了。感谢您的耐心和及时回复。

**Comment by thisisqiaoqiao** [comment]
下载好像遇到超时问题了
![image](https://github.com/cropandweed/cropandweed-dataset/assets/127526922/40cf03b7-efa9-420e-8345-8a3ca6328d55)
![image](https://github.com/cropandweed/cropandweed-dataset/assets/127526922/eec57744-4509-4827-b226-d31763c4f247)

**Comment by steiningerd** [comment]
Unfortunately, I cannot reproduce your problem. It might be related to your internet connection.

**Comment by thisisqiaoqiao** [comment]
好的，谢谢。
