### ISSUE TITLE
您好，我在跑map_dataset.py时碰到以下问题

### ISSUE THREAD

**Issue by 1972998383** [cropandweed/cropandweed-dataset#5]

**Comment by 1972998383** [comment]
usage: map_dataset.py [-h] [--bboxes BBOXES] [--labelids LABELIDS]
                      [--dataset_source DATASET_SOURCE] --dataset_target
                      DATASET_TARGET
map_dataset.py: error: the following arguments are required: --dataset_target
请问def parse_arguments():
    parser = argparse.ArgumentParser(description='map annotated classes between datasets')
    parser.add_argument('--bboxes', type=str, default='../data/bboxes',
                        help='directory for input and output bounding-box annotations as csv files in sub-directories '
                             'for each target_dataset variant')
    parser.add_argument('--labelids', type=str, default='../data/labelIds',
                        help='source directory for input and output semantic masks as single-channel png images '
                             'in sub-directories for each target_dataset variant')
    parser.add_argument('--dataset_source', type=str, default='CropAndWeed', help='name of source target_dataset')
    parser.add_argument('--dataset_target', type=str, default='target_dataset', required=True, help='name of target target_dataset')
    return parser.parse_args()能否举个例子

**Comment by 1972998383** [comment]
除了在github上下载的代码和setup.py下载数据集，还要下载什么才能跑这个实验

**Comment by steiningerd** [comment]
As indicated by the error message, you have to set the argument '--dataset_target'. For a usage example and further information please see section "Dataset Variants" in the Readme.

**Comment by 1972998383** [comment]
Thankyou，我是一个新手，请问自述文件中的“数据集变体”中预定义的变体 CropsOrWeed9是需要自己新建一个名为 CropsOrWeed9的空文件夹吗

**Comment by steiningerd** [comment]
All required directories should be created automatically.

**Comment by 1972998383** [comment]
def parse_arguments():
parser = argparse.ArgumentParser(description='map annotated classes between datasets')
parser.add_argument('--bboxes', type=str, default='../data/bboxes',
help='directory for input and output bounding-box annotations as csv files in sub-directories '
'for each target_dataset variant')
parser.add_argument('--labelids', type=str, default='../data/labelIds',
help='source directory for input and output semantic masks as single-channel png images '
'in sub-directories for each target_dataset variant')
parser.add_argument('--dataset_source', type=str, default='CropAndWeed', help='name of source target_dataset')
parser.add_argument('--dataset_target', type=str, default='CropOrWeed9', required=True, help='name of target target_dataset')
return parser.parse_args()
这里你可以展示你是怎么设置参数的吗，谢谢

**Comment by steiningerd** [comment]
You don't have to change the source code and I would recommend to download the original script again. Just add --dataset_target CropOrWeed9 when calling the script.

**Comment by 1972998383** [comment]
是的，我重新下载了脚本，只是添加了parser.add_argument('--dataset_target', type=str, default='CropOrWeed9', required=True, help='name of target dataset')
但是还是报错map_dataset.py: error: the following arguments are required: --dataset_target

**Comment by steiningerd** [comment]
You don't have to edit the source code - just call the script like the example in the Readme.

map_dataset.py --dataset_target CropsOrWeed9

**Comment by 1972998383** [comment]
Thank you for your patience，I have solve the problem
