### ISSUE TITLE
no access to the dataset

### ISSUE THREAD

**Issue by RichelieuGVG1** [cropandweed/cropandweed-dataset#7]
Dear colleagues, we would really like to download your dataset for our educational purposes, but we cannot do this, since the link provided in your dataset downloader (setup.py) is not working (there is no access). Please tell me how we can download your dataset?

**Comment by steiningerd** [comment]
I just verified that all 5 tar-files in the download folder are accessible and can be downloaded. The access to the folder itself is restricted intentionally. I would suggest to run the script setup.py.
