### ISSUE TITLE
Slow download speed and unaccessable URL

### ISSUE THREAD

**Issue by user23604** [cropandweed/cropandweed-dataset#8]
Why do these files download so slowly when I run set_up.py, and I can't access the URL: https://vitro-testing.com/wp-content/uploads/2022/12/ (Forbidden
You don't have permission to access this resource.) to download through other software.
![image](https://github.com/user-attachments/assets/4f37c0bf-21a5-4a58-82fa-ede0c6d2c716)

![image](https://github.com/user-attachments/assets/281ceea0-17be-4530-9cc6-e0f1bb512785)

**Comment by steiningerd** [comment]
Access to the top-level folder is restricted intentionally. The dataset should be downloaded using the script setup.py. While downloading the annotations is fast, the images can take some time (depending on your internet connection and server load). Just be patient and let me know if there are any other problems.
